name: Hey CI/CD

# Trigger the workflow on any push or pull request
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Add a sample test file (for demonstration purposes)
      - name: Add sample test file
        run: |
          echo "def test_sample():" > test_sample.py
          echo "    assert 1 + 1 == 2" >> test_sample.py

      # Step 5: Run tests
      - name: Run tests
        run: pytest

  merge-to-main:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - uses: actions/checkout@v2
      
      # Step 6: Merge to main branch if tests pass
      - name: Merge to main
        run: |
          git config --global user.name 'sandesh.kumar@databricks.com'
          git config --global user.email 'Sandesh Kumar'
          git fetch origin main
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.pull_request.number }}"
          git push origin main
